verbose = true

baseURL = "https://caiustheory.com"
title = "Caius Theory"
theme = "caiustheory"

languageCode = "en-gb"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"

disableKinds = ["section", "taxonomyTerm"]

# Turn on Ugly URLs for everything (/slug.format)
# We then override this for all formats except plaintext for pretty urls
uglyurls = true

enableGitInfo = true

[params]
description = "Now with even more cowbell…"

[taxonomies]
tag = "tag"

# We don't want no stinking dates in our permalinks
[permalinks]
post = "/:slug/"

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false

[mediaTypes]
  [mediaTypes."text/markdown"]
  suffixes = ["text"]

[outputFormats]
  [outputFormats.HTML]
  noUgly = true

  # Let the magic happen for /:slug.text
  [outputFormats.PlainText]
  mediaType = "text/markdown"
  baseName = "index"
  isPlainText = true
  noUgly = false
  rel = "alternate"

  [outputFormats.RSSFeed]
  mediaType = "application/rss"
  baseName = "feed"

  [outputFormats.JSONFeed]
  mediaType = "application/json"
  baseName = "feed"

[outputs]
page = ["HTML", "PlainText"]
home = ["HTML", "RSSFeed", "JSONFeed"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[author]
  name = "Caius Durling"
