verbose = true

baseURL = "http://caiustheory.com/"
theme = "caiustheory"

languageCode = "en-gb"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"

disableKinds = ["section", "taxonomyTerm"]

[taxonomies]
tag = "tag"

# We don't want no stinking dates in our permalinks
[permalinks]
post = "/:slug/"

[outputFormats]

# Let the magic happen for /:slug.text
[outputFormats.PlainText]
mediaType = "text/plain"
isPlainText = true

[outputs]
page = ["HTML", "PlainText"]
home = ["HTML", "RSS"]

[blackfriday]
smartypants = false
smartDashes = false
extensions = ["strikethrough", "footnotes", "autoHeaderIds"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[author]
  name = "Caius Durling"
