---
name: Build caiustheory

"on":
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Nix Quick Install
        uses: nixbuild/nix-quick-install-action@v9

      - name: Build
        run: nix develop . --command hugo --gc --minify --cleanDestinationDir
